platform :ios, '13.0'
use_frameworks!

target 'Pindex' do

	# Pods for Pindex

	# Firebase
	pod 'Firebase/Core'
	pod 'FirebaseFirestore'
	pod 'Firebase/Auth'
    	pod 'Firebase/Core'
    	pod 'Firebase/Storage'
    	pod 'Firebase/Database'

	# Facebook
	pod 'FacebookCore'
	pod 'FacebookSDK'
	pod 'FacebookSDK/LoginKit'
	pod 'FacebookSDK/ShareKit'
	pod 'FacebookSDK/PlacesKit'
	pod 'FacebookLogin'
  pod 'FBSDKLoginKit'

end
