platform :ios, '13.0'

target 'Pindex' do
	# Pods for Pindex
	pod 'Firebase/Core'
	pod 'FirebaseFirestore'
	pod 'Firebase/Auth'
    	pod 'Firebase/Core'
    	pod 'Firebase/Storage'
    	pod 'Firebase/Database'
end