platform :ios, '13.0'
use_frameworks!

target 'Pindex' do

	# Pods for Pindex

	# Firebase
	pod 'Firebase/Core'
  pod 'Firebase/Database'
	pod 'Firebase/Firestore'
	pod 'Firebase/Auth'
  pod "BCryptSwift"
  
  target 'PindexTests' do
      inherit! :search_paths
      	# Firebase
	pod 'Firebase/Core'
  pod 'Firebase/Database'
	pod 'Firebase/Firestore'
	pod 'Firebase/Auth'

  end

end
